// Generated by gencpp from file kinfu_ros/GetTSDFRequest.msg
// DO NOT EDIT!


#ifndef KINFU_ROS_MESSAGE_GETTSDFREQUEST_H
#define KINFU_ROS_MESSAGE_GETTSDFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinfu_ros
{
template <class ContainerAllocator>
struct GetTSDFRequest_
{
  typedef GetTSDFRequest_<ContainerAllocator> Type;

  GetTSDFRequest_()
    {
    }
  GetTSDFRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTSDFRequest_

typedef ::kinfu_ros::GetTSDFRequest_<std::allocator<void> > GetTSDFRequest;

typedef boost::shared_ptr< ::kinfu_ros::GetTSDFRequest > GetTSDFRequestPtr;
typedef boost::shared_ptr< ::kinfu_ros::GetTSDFRequest const> GetTSDFRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinfu_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'kinfu_ros': ['/home/karo/Desktop/DeepLeaveSegmentation/catkin_ws/src/kinfu_ros-master/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::kinfu_ros::GetTSDFRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinfu_ros/GetTSDFRequest";
  }

  static const char* value(const ::kinfu_ros::GetTSDFRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::kinfu_ros::GetTSDFRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTSDFRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinfu_ros::GetTSDFRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::kinfu_ros::GetTSDFRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // KINFU_ROS_MESSAGE_GETTSDFREQUEST_H
