// Generated by gencpp from file kinfu_ros/GetTSDF.msg
// DO NOT EDIT!


#ifndef KINFU_ROS_MESSAGE_GETTSDF_H
#define KINFU_ROS_MESSAGE_GETTSDF_H

#include <ros/service_traits.h>


#include <kinfu_ros/GetTSDFRequest.h>
#include <kinfu_ros/GetTSDFResponse.h>


namespace kinfu_ros
{

struct GetTSDF
{

typedef GetTSDFRequest Request;
typedef GetTSDFResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTSDF
} // namespace kinfu_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinfu_ros::GetTSDF > {
  static const char* value()
  {
    return "5396807193e5f6302680576158283a3a";
  }

  static const char* value(const ::kinfu_ros::GetTSDF&) { return value(); }
};

template<>
struct DataType< ::kinfu_ros::GetTSDF > {
  static const char* value()
  {
    return "kinfu_ros/GetTSDF";
  }

  static const char* value(const ::kinfu_ros::GetTSDF&) { return value(); }
};


// service_traits::MD5Sum< ::kinfu_ros::GetTSDFRequest> should match 
// service_traits::MD5Sum< ::kinfu_ros::GetTSDF > 
template<>
struct MD5Sum< ::kinfu_ros::GetTSDFRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinfu_ros::GetTSDF >::value();
  }
  static const char* value(const ::kinfu_ros::GetTSDFRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinfu_ros::GetTSDFRequest> should match 
// service_traits::DataType< ::kinfu_ros::GetTSDF > 
template<>
struct DataType< ::kinfu_ros::GetTSDFRequest>
{
  static const char* value()
  {
    return DataType< ::kinfu_ros::GetTSDF >::value();
  }
  static const char* value(const ::kinfu_ros::GetTSDFRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinfu_ros::GetTSDFResponse> should match 
// service_traits::MD5Sum< ::kinfu_ros::GetTSDF > 
template<>
struct MD5Sum< ::kinfu_ros::GetTSDFResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinfu_ros::GetTSDF >::value();
  }
  static const char* value(const ::kinfu_ros::GetTSDFResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinfu_ros::GetTSDFResponse> should match 
// service_traits::DataType< ::kinfu_ros::GetTSDF > 
template<>
struct DataType< ::kinfu_ros::GetTSDFResponse>
{
  static const char* value()
  {
    return DataType< ::kinfu_ros::GetTSDF >::value();
  }
  static const char* value(const ::kinfu_ros::GetTSDFResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINFU_ROS_MESSAGE_GETTSDF_H
